PhotographyTool.create!(name:"lightbox کوچکتر از ۴۰ سانتی متر")
PhotographyTool.create!(name:"lightbox بزرگتر از ۴۰ سانتی متر")
PhotographyTool.create!(name:"نور ثابت یا فلاش")
PhotographyTool.create!(name:"پایه نور")
PhotographyTool.create!(name:"Diffuser")
PhotographyTool.create!(name:"فلش اکسترنال (External Flash)")
PhotographyTool.create!(name:"ریموت")
PhotographyTool.create!(name:"پرده فون")

Kit.create!(title:"small_product_kit", persian_title:"کیت کوچک عکاسی محصول")
Kit.create!(title:"large_product_kit", persian_title:"کیت بزرگ عکاسی محصول")
Kit.create!(title:"portable_light", persian_title:"کیت نور پرتابل")
Kit.create!(title:"dual_light_studio_kit", persian_title:"کیت نور دوتایی")
Kit.create!(title:"portable_studio_kit", persian_title:"کیت استودیوی پرتابل")

kit = Kit.find_by_title("small_product_kit")
tool = PhotographyTool.find_by_name("lightbox کوچکتر از ۴۰ سانتی متر")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:0)
tool = PhotographyTool.find_by_name("نور ثابت یا فلاش")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:2)
tool = PhotographyTool.find_by_name("پایه نور")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:2)
tool = PhotographyTool.find_by_name("Diffuser")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:2)

kit = Kit.find_by_title("large_product_kit")
tool = PhotographyTool.find_by_name("lightbox بزرگتر از ۴۰ سانتی متر")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:0)
tool = PhotographyTool.find_by_name("نور ثابت یا فلاش")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:2)
tool = PhotographyTool.find_by_name("پایه نور")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:2)
tool = PhotographyTool.find_by_name("Diffuser")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:2)

kit = Kit.find_by_title("portable_light")
tool = PhotographyTool.find_by_name("فلش اکسترنال (External Flash)")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:1)
tool = PhotographyTool.find_by_name("پایه نور")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:1)
tool = PhotographyTool.find_by_name("ریموت")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:1)
tool = PhotographyTool.find_by_name("Diffuser")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:1)

kit = Kit.find_by_title("dual_light_studio_kit")
tool = PhotographyTool.find_by_name("نور ثابت یا فلاش")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:2)
tool = PhotographyTool.find_by_name("پایه نور")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:2)
tool = PhotographyTool.find_by_name("Diffuser")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:2)

kit = Kit.find_by_title("portable_studio_kit")
tool = PhotographyTool.find_by_name("پرده فون")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:1)
tool = PhotographyTool.find_by_name("نور ثابت یا فلاش")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:2)
tool = PhotographyTool.find_by_name("پایه نور")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:2)
tool = PhotographyTool.find_by_name("Diffuser")
KitPhotographyTool.create!(kit_id:kit.id, photography_tool_id:tool.id,count:2)
