JoinStep.find_or_create_by(name: 'اطلاعات اولیه', code: 1)
JoinStep.find_or_create_by(name: 'اطلاعات مکانی', code: 2)
JoinStep.find_or_create_by(name: 'تجهیزات عکاسی', code: 3)
JoinStep.find_or_create_by(name: 'نمونه کارها', code: 4)
JoinStep.find_or_create_by(name: 'تجربه کاری', code: 5)
JoinStep.find_or_create_by(name: 'تاییدیه', code: 6)
JoinStep.find_or_create_by(name: 'پروفایل ناقص', code: 5)
JoinStep.find_or_create_by(name: 'تایید اما ناقص', code: 5)
JoinStep.find_or_create_by(name: 'تایید مسئول', code: 5)
JoinStep.find_or_create_by(name: 'در انتظار مصاحبه', code: 5)
JoinStep.find_or_create_by(name: 'تاریخ مصاحبه', code: 5)
JoinStep.find_or_create_by(name: 'حقوقی', code: 5)
JoinStep.find_or_create_by(name: 'لغو عضویت', code: 13)
JoinStep.find_or_create_by(name: 'بازنگری', code: 5)
JoinStep.find_or_create_by(name: 'تایید نهایی', code: 5)

