development:
  cloud_name: kadro
  api_key: '385769327545433'
  api_secret: QKxXe2zIjouMoCzf8n9BaKjBNms
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: kadro
  api_key: '385769327545433'
  api_secret: QKxXe2zIjouMoCzf8n9BaKjBNms
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: kadro
  api_key: '385769327545433'
  api_secret: QKxXe2zIjouMoCzf8n9BaKjBNms
  enhance_image_tag: true
  static_image_support: false
staging:
    cloud_name: kadro
    api_key: '385769327545433'
    api_secret: QKxXe2zIjouMoCzf8n9BaKjBNms
    enhance_image_tag: true
    static_image_support: false
