default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: deploy
  password: 12345678
  host: localhost
  port: 5432

development:
  <<: *default
  database: kadro_en_db

test:
  <<: *default
  database: kadro_en_db_test

production:
  <<: *default
  database: kadro_en_db

