default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: amirmahdivaleh
  host: localhost
  port: 5432

development:
  <<: *default
  database: kadro_db_en

test:
  <<: *default
  database: kadro_db_en_test

production:
  <<: *default
  database: kadro_db_en