###################################
### GENERAL, HEADER & META TAGS ###
###################################

logo: ""                                                                        # Logo for your blog. Leave empty if you don't have one
blog_name: "Say Cheese!"                                                              # Give your blog a meanungful name.
title: "Latest News"             # Give your blog a meaningful title. This is used for the HTML title attribute
title_short: "Kadro"                                                            # Place the name of your blog or a short title here
short_description: "Latest Kadro News"         # Short description for your blog
meta_description: "Latest Kadro News"  # meta description tag
meta_author: "Amirmahdi Valeh Valeh                                                         # meta tag for author
keywords: "kadro, photography, NEWS"                                          # your keywords
og_logo: "https://opoloo.github.io/lines-engine/assets/images/lines-logo.jpg"   # OpenGraph logo
geo_position: "35.7242574; 51.3870327"                                                     # Geo tags for position and address
geo_address: "Kadro Head Quearters, University of Tehran, North Kargar, Tehran, Iran"                                              # Geo tags for position and address


##############
### SOCIAL ###
##############

# Your Twitter and Google+ profile URL
# Leave empty if you don't want to display inside the footer
twitter_url: 'http://twitter.com/kadro_co'


#################
### ATOM FEED ###
#################

feed_title: "Kadro | Latest Updates and NEWS"        # give your feed a title
feed_logo: "/img/updateslogo.png" # full URL to the feed logo. Aspect ratio should be 2:1
feed_favicon: "/img/favicon.png" # full URL to the favicon. Aspect ratio should be 1:1


#####################
### APP SPECIFICS ###
#####################

refresh_sitemap: false

hero_images: ["lines_default_01.png", "lines_default_02.png", "lines_default_03.png"]

articles_per_page: 10 # Pagination: How many articles should be desplayed per page?

# Your apps secret token. Generate a new one with 'rake secret' and paste it below
secret_token: "afa4a436180a2febe9b814c6a57b6f3ad298aa82ce0ab4c9e8238713764b665e978f9fad8146587b6cf4a518de4a8f0eac1156cf43a778548e0082629d099fef"

# Environment dependent configuration. Place your URLs here
development:
  host: "updates.localhost:3000"
  from_email: 'support@kadro.me'
test:
  host: "test.local"
  from_email: 'support@kadro.me'
production:
  host: "updates.kadro.me"
  from_email: 'support@kadro.me'
